/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MoreRouteImport } from './routes/more'
import { Route as ListenRouteImport } from './routes/listen'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DataPolicyRouteImport } from './routes/data-policy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReadIndexRouteImport } from './routes/read.index'
import { Route as MoreIndexRouteImport } from './routes/more.index'
import { Route as ReadSurahNumberRouteImport } from './routes/read.$surahNumber'
import { Route as MoreZakatCalculatorRouteImport } from './routes/more.zakat-calculator'
import { Route as MoreThemesRouteImport } from './routes/more.themes'
import { Route as MoreTasbeehRouteImport } from './routes/more.tasbeeh'
import { Route as MoreSettingsRouteImport } from './routes/more.settings'
import { Route as MoreSalatNabiRouteImport } from './routes/more.salat-nabi'
import { Route as MoreRuqyahRouteImport } from './routes/more.ruqyah'
import { Route as MoreQuranLearningRouteImport } from './routes/more.quran-learning'
import { Route as MoreQiblaRouteImport } from './routes/more.qibla'
import { Route as MoreProphetsStoriesRouteImport } from './routes/more.prophets-stories'
import { Route as MorePrayerTimesRouteImport } from './routes/more.prayer-times'
import { Route as MoreNamesRouteImport } from './routes/more.names'
import { Route as MoreIslamicEducationRouteImport } from './routes/more.islamic-education'
import { Route as MoreHijriCalendarRouteImport } from './routes/more.hijri-calendar'
import { Route as MoreDownloadsRouteImport } from './routes/more.downloads'
import { Route as MoreAthkarRouteImport } from './routes/more.athkar'
import { Route as MoreHadithIndexRouteImport } from './routes/more.hadith.index'
import { Route as MoreHadithBookRouteImport } from './routes/more.hadith.$book'
import { Route as ApiPublicVersionRouteImport } from './routes/api/public/version'
import { Route as ApiPublicTtsSalatNabiDotmp3RouteImport } from './routes/api/public/tts.salat-nabi[.]mp3'
import { Route as ApiPublicTtsRuqyahRouteImport } from './routes/api/public/tts.ruqyah'
import { Route as ApiPublicTtsProphetStoryRouteImport } from './routes/api/public/tts.prophet-story'
import { Route as ApiPublicPushUnsubscribeRouteImport } from './routes/api/public/push.unsubscribe'
import { Route as ApiPublicPushSubscribeRouteImport } from './routes/api/public/push.subscribe'
import { Route as ApiPublicPushCronRouteImport } from './routes/api/public/push.cron'
import { Route as ApiPublicPushAnnounceUpdateRouteImport } from './routes/api/public/push.announce-update'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const ListenRoute = ListenRouteImport.update({
  id: '/listen',
  path: '/listen',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DataPolicyRoute = DataPolicyRouteImport.update({
  id: '/data-policy',
  path: '/data-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadIndexRoute = ReadIndexRouteImport.update({
  id: '/read/',
  path: '/read/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreIndexRoute = MoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MoreRoute,
} as any)
const ReadSurahNumberRoute = ReadSurahNumberRouteImport.update({
  id: '/read/$surahNumber',
  path: '/read/$surahNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreZakatCalculatorRoute = MoreZakatCalculatorRouteImport.update({
  id: '/zakat-calculator',
  path: '/zakat-calculator',
  getParentRoute: () => MoreRoute,
} as any)
const MoreThemesRoute = MoreThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => MoreRoute,
} as any)
const MoreTasbeehRoute = MoreTasbeehRouteImport.update({
  id: '/tasbeeh',
  path: '/tasbeeh',
  getParentRoute: () => MoreRoute,
} as any)
const MoreSettingsRoute = MoreSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MoreRoute,
} as any)
const MoreSalatNabiRoute = MoreSalatNabiRouteImport.update({
  id: '/salat-nabi',
  path: '/salat-nabi',
  getParentRoute: () => MoreRoute,
} as any)
const MoreRuqyahRoute = MoreRuqyahRouteImport.update({
  id: '/ruqyah',
  path: '/ruqyah',
  getParentRoute: () => MoreRoute,
} as any)
const MoreQuranLearningRoute = MoreQuranLearningRouteImport.update({
  id: '/quran-learning',
  path: '/quran-learning',
  getParentRoute: () => MoreRoute,
} as any)
const MoreQiblaRoute = MoreQiblaRouteImport.update({
  id: '/qibla',
  path: '/qibla',
  getParentRoute: () => MoreRoute,
} as any)
const MoreProphetsStoriesRoute = MoreProphetsStoriesRouteImport.update({
  id: '/prophets-stories',
  path: '/prophets-stories',
  getParentRoute: () => MoreRoute,
} as any)
const MorePrayerTimesRoute = MorePrayerTimesRouteImport.update({
  id: '/prayer-times',
  path: '/prayer-times',
  getParentRoute: () => MoreRoute,
} as any)
const MoreNamesRoute = MoreNamesRouteImport.update({
  id: '/names',
  path: '/names',
  getParentRoute: () => MoreRoute,
} as any)
const MoreIslamicEducationRoute = MoreIslamicEducationRouteImport.update({
  id: '/islamic-education',
  path: '/islamic-education',
  getParentRoute: () => MoreRoute,
} as any)
const MoreHijriCalendarRoute = MoreHijriCalendarRouteImport.update({
  id: '/hijri-calendar',
  path: '/hijri-calendar',
  getParentRoute: () => MoreRoute,
} as any)
const MoreDownloadsRoute = MoreDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => MoreRoute,
} as any)
const MoreAthkarRoute = MoreAthkarRouteImport.update({
  id: '/athkar',
  path: '/athkar',
  getParentRoute: () => MoreRoute,
} as any)
const MoreHadithIndexRoute = MoreHadithIndexRouteImport.update({
  id: '/hadith/',
  path: '/hadith/',
  getParentRoute: () => MoreRoute,
} as any)
const MoreHadithBookRoute = MoreHadithBookRouteImport.update({
  id: '/hadith/$book',
  path: '/hadith/$book',
  getParentRoute: () => MoreRoute,
} as any)
const ApiPublicVersionRoute = ApiPublicVersionRouteImport.update({
  id: '/api/public/version',
  path: '/api/public/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTtsSalatNabiDotmp3Route =
  ApiPublicTtsSalatNabiDotmp3RouteImport.update({
    id: '/api/public/tts/salat-nabi.mp3',
    path: '/api/public/tts/salat-nabi.mp3',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTtsRuqyahRoute = ApiPublicTtsRuqyahRouteImport.update({
  id: '/api/public/tts/ruqyah',
  path: '/api/public/tts/ruqyah',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTtsProphetStoryRoute =
  ApiPublicTtsProphetStoryRouteImport.update({
    id: '/api/public/tts/prophet-story',
    path: '/api/public/tts/prophet-story',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPushUnsubscribeRoute =
  ApiPublicPushUnsubscribeRouteImport.update({
    id: '/api/public/push/unsubscribe',
    path: '/api/public/push/unsubscribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPushSubscribeRoute = ApiPublicPushSubscribeRouteImport.update({
  id: '/api/public/push/subscribe',
  path: '/api/public/push/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushCronRoute = ApiPublicPushCronRouteImport.update({
  id: '/api/public/push/cron',
  path: '/api/public/push/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushAnnounceUpdateRoute =
  ApiPublicPushAnnounceUpdateRouteImport.update({
    id: '/api/public/push/announce-update',
    path: '/api/public/push/announce-update',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/data-policy': typeof DataPolicyRoute
  '/favorites': typeof FavoritesRoute
  '/listen': typeof ListenRoute
  '/more': typeof MoreRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/more/athkar': typeof MoreAthkarRoute
  '/more/downloads': typeof MoreDownloadsRoute
  '/more/hijri-calendar': typeof MoreHijriCalendarRoute
  '/more/islamic-education': typeof MoreIslamicEducationRoute
  '/more/names': typeof MoreNamesRoute
  '/more/prayer-times': typeof MorePrayerTimesRoute
  '/more/prophets-stories': typeof MoreProphetsStoriesRoute
  '/more/qibla': typeof MoreQiblaRoute
  '/more/quran-learning': typeof MoreQuranLearningRoute
  '/more/ruqyah': typeof MoreRuqyahRoute
  '/more/salat-nabi': typeof MoreSalatNabiRoute
  '/more/settings': typeof MoreSettingsRoute
  '/more/tasbeeh': typeof MoreTasbeehRoute
  '/more/themes': typeof MoreThemesRoute
  '/more/zakat-calculator': typeof MoreZakatCalculatorRoute
  '/read/$surahNumber': typeof ReadSurahNumberRoute
  '/more/': typeof MoreIndexRoute
  '/read/': typeof ReadIndexRoute
  '/api/public/version': typeof ApiPublicVersionRoute
  '/more/hadith/$book': typeof MoreHadithBookRoute
  '/more/hadith/': typeof MoreHadithIndexRoute
  '/api/public/push/announce-update': typeof ApiPublicPushAnnounceUpdateRoute
  '/api/public/push/cron': typeof ApiPublicPushCronRoute
  '/api/public/push/subscribe': typeof ApiPublicPushSubscribeRoute
  '/api/public/push/unsubscribe': typeof ApiPublicPushUnsubscribeRoute
  '/api/public/tts/prophet-story': typeof ApiPublicTtsProphetStoryRoute
  '/api/public/tts/ruqyah': typeof ApiPublicTtsRuqyahRoute
  '/api/public/tts/salat-nabi.mp3': typeof ApiPublicTtsSalatNabiDotmp3Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/data-policy': typeof DataPolicyRoute
  '/favorites': typeof FavoritesRoute
  '/listen': typeof ListenRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/more/athkar': typeof MoreAthkarRoute
  '/more/downloads': typeof MoreDownloadsRoute
  '/more/hijri-calendar': typeof MoreHijriCalendarRoute
  '/more/islamic-education': typeof MoreIslamicEducationRoute
  '/more/names': typeof MoreNamesRoute
  '/more/prayer-times': typeof MorePrayerTimesRoute
  '/more/prophets-stories': typeof MoreProphetsStoriesRoute
  '/more/qibla': typeof MoreQiblaRoute
  '/more/quran-learning': typeof MoreQuranLearningRoute
  '/more/ruqyah': typeof MoreRuqyahRoute
  '/more/salat-nabi': typeof MoreSalatNabiRoute
  '/more/settings': typeof MoreSettingsRoute
  '/more/tasbeeh': typeof MoreTasbeehRoute
  '/more/themes': typeof MoreThemesRoute
  '/more/zakat-calculator': typeof MoreZakatCalculatorRoute
  '/read/$surahNumber': typeof ReadSurahNumberRoute
  '/more': typeof MoreIndexRoute
  '/read': typeof ReadIndexRoute
  '/api/public/version': typeof ApiPublicVersionRoute
  '/more/hadith/$book': typeof MoreHadithBookRoute
  '/more/hadith': typeof MoreHadithIndexRoute
  '/api/public/push/announce-update': typeof ApiPublicPushAnnounceUpdateRoute
  '/api/public/push/cron': typeof ApiPublicPushCronRoute
  '/api/public/push/subscribe': typeof ApiPublicPushSubscribeRoute
  '/api/public/push/unsubscribe': typeof ApiPublicPushUnsubscribeRoute
  '/api/public/tts/prophet-story': typeof ApiPublicTtsProphetStoryRoute
  '/api/public/tts/ruqyah': typeof ApiPublicTtsRuqyahRoute
  '/api/public/tts/salat-nabi.mp3': typeof ApiPublicTtsSalatNabiDotmp3Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/data-policy': typeof DataPolicyRoute
  '/favorites': typeof FavoritesRoute
  '/listen': typeof ListenRoute
  '/more': typeof MoreRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/more/athkar': typeof MoreAthkarRoute
  '/more/downloads': typeof MoreDownloadsRoute
  '/more/hijri-calendar': typeof MoreHijriCalendarRoute
  '/more/islamic-education': typeof MoreIslamicEducationRoute
  '/more/names': typeof MoreNamesRoute
  '/more/prayer-times': typeof MorePrayerTimesRoute
  '/more/prophets-stories': typeof MoreProphetsStoriesRoute
  '/more/qibla': typeof MoreQiblaRoute
  '/more/quran-learning': typeof MoreQuranLearningRoute
  '/more/ruqyah': typeof MoreRuqyahRoute
  '/more/salat-nabi': typeof MoreSalatNabiRoute
  '/more/settings': typeof MoreSettingsRoute
  '/more/tasbeeh': typeof MoreTasbeehRoute
  '/more/themes': typeof MoreThemesRoute
  '/more/zakat-calculator': typeof MoreZakatCalculatorRoute
  '/read/$surahNumber': typeof ReadSurahNumberRoute
  '/more/': typeof MoreIndexRoute
  '/read/': typeof ReadIndexRoute
  '/api/public/version': typeof ApiPublicVersionRoute
  '/more/hadith/$book': typeof MoreHadithBookRoute
  '/more/hadith/': typeof MoreHadithIndexRoute
  '/api/public/push/announce-update': typeof ApiPublicPushAnnounceUpdateRoute
  '/api/public/push/cron': typeof ApiPublicPushCronRoute
  '/api/public/push/subscribe': typeof ApiPublicPushSubscribeRoute
  '/api/public/push/unsubscribe': typeof ApiPublicPushUnsubscribeRoute
  '/api/public/tts/prophet-story': typeof ApiPublicTtsProphetStoryRoute
  '/api/public/tts/ruqyah': typeof ApiPublicTtsRuqyahRoute
  '/api/public/tts/salat-nabi.mp3': typeof ApiPublicTtsSalatNabiDotmp3Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/data-policy'
    | '/favorites'
    | '/listen'
    | '/more'
    | '/privacy'
    | '/progress'
    | '/search'
    | '/terms'
    | '/more/athkar'
    | '/more/downloads'
    | '/more/hijri-calendar'
    | '/more/islamic-education'
    | '/more/names'
    | '/more/prayer-times'
    | '/more/prophets-stories'
    | '/more/qibla'
    | '/more/quran-learning'
    | '/more/ruqyah'
    | '/more/salat-nabi'
    | '/more/settings'
    | '/more/tasbeeh'
    | '/more/themes'
    | '/more/zakat-calculator'
    | '/read/$surahNumber'
    | '/more/'
    | '/read/'
    | '/api/public/version'
    | '/more/hadith/$book'
    | '/more/hadith/'
    | '/api/public/push/announce-update'
    | '/api/public/push/cron'
    | '/api/public/push/subscribe'
    | '/api/public/push/unsubscribe'
    | '/api/public/tts/prophet-story'
    | '/api/public/tts/ruqyah'
    | '/api/public/tts/salat-nabi.mp3'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/data-policy'
    | '/favorites'
    | '/listen'
    | '/privacy'
    | '/progress'
    | '/search'
    | '/terms'
    | '/more/athkar'
    | '/more/downloads'
    | '/more/hijri-calendar'
    | '/more/islamic-education'
    | '/more/names'
    | '/more/prayer-times'
    | '/more/prophets-stories'
    | '/more/qibla'
    | '/more/quran-learning'
    | '/more/ruqyah'
    | '/more/salat-nabi'
    | '/more/settings'
    | '/more/tasbeeh'
    | '/more/themes'
    | '/more/zakat-calculator'
    | '/read/$surahNumber'
    | '/more'
    | '/read'
    | '/api/public/version'
    | '/more/hadith/$book'
    | '/more/hadith'
    | '/api/public/push/announce-update'
    | '/api/public/push/cron'
    | '/api/public/push/subscribe'
    | '/api/public/push/unsubscribe'
    | '/api/public/tts/prophet-story'
    | '/api/public/tts/ruqyah'
    | '/api/public/tts/salat-nabi.mp3'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/data-policy'
    | '/favorites'
    | '/listen'
    | '/more'
    | '/privacy'
    | '/progress'
    | '/search'
    | '/terms'
    | '/more/athkar'
    | '/more/downloads'
    | '/more/hijri-calendar'
    | '/more/islamic-education'
    | '/more/names'
    | '/more/prayer-times'
    | '/more/prophets-stories'
    | '/more/qibla'
    | '/more/quran-learning'
    | '/more/ruqyah'
    | '/more/salat-nabi'
    | '/more/settings'
    | '/more/tasbeeh'
    | '/more/themes'
    | '/more/zakat-calculator'
    | '/read/$surahNumber'
    | '/more/'
    | '/read/'
    | '/api/public/version'
    | '/more/hadith/$book'
    | '/more/hadith/'
    | '/api/public/push/announce-update'
    | '/api/public/push/cron'
    | '/api/public/push/subscribe'
    | '/api/public/push/unsubscribe'
    | '/api/public/tts/prophet-story'
    | '/api/public/tts/ruqyah'
    | '/api/public/tts/salat-nabi.mp3'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DataPolicyRoute: typeof DataPolicyRoute
  FavoritesRoute: typeof FavoritesRoute
  ListenRoute: typeof ListenRoute
  MoreRoute: typeof MoreRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProgressRoute: typeof ProgressRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  ReadSurahNumberRoute: typeof ReadSurahNumberRoute
  ReadIndexRoute: typeof ReadIndexRoute
  ApiPublicVersionRoute: typeof ApiPublicVersionRoute
  ApiPublicPushAnnounceUpdateRoute: typeof ApiPublicPushAnnounceUpdateRoute
  ApiPublicPushCronRoute: typeof ApiPublicPushCronRoute
  ApiPublicPushSubscribeRoute: typeof ApiPublicPushSubscribeRoute
  ApiPublicPushUnsubscribeRoute: typeof ApiPublicPushUnsubscribeRoute
  ApiPublicTtsProphetStoryRoute: typeof ApiPublicTtsProphetStoryRoute
  ApiPublicTtsRuqyahRoute: typeof ApiPublicTtsRuqyahRoute
  ApiPublicTtsSalatNabiDotmp3Route: typeof ApiPublicTtsSalatNabiDotmp3Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listen': {
      id: '/listen'
      path: '/listen'
      fullPath: '/listen'
      preLoaderRoute: typeof ListenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-policy': {
      id: '/data-policy'
      path: '/data-policy'
      fullPath: '/data-policy'
      preLoaderRoute: typeof DataPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/': {
      id: '/read/'
      path: '/read'
      fullPath: '/read/'
      preLoaderRoute: typeof ReadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more/': {
      id: '/more/'
      path: '/'
      fullPath: '/more/'
      preLoaderRoute: typeof MoreIndexRouteImport
      parentRoute: typeof MoreRoute
    }
    '/read/$surahNumber': {
      id: '/read/$surahNumber'
      path: '/read/$surahNumber'
      fullPath: '/read/$surahNumber'
      preLoaderRoute: typeof ReadSurahNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more/zakat-calculator': {
      id: '/more/zakat-calculator'
      path: '/zakat-calculator'
      fullPath: '/more/zakat-calculator'
      preLoaderRoute: typeof MoreZakatCalculatorRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/themes': {
      id: '/more/themes'
      path: '/themes'
      fullPath: '/more/themes'
      preLoaderRoute: typeof MoreThemesRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/tasbeeh': {
      id: '/more/tasbeeh'
      path: '/tasbeeh'
      fullPath: '/more/tasbeeh'
      preLoaderRoute: typeof MoreTasbeehRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/settings': {
      id: '/more/settings'
      path: '/settings'
      fullPath: '/more/settings'
      preLoaderRoute: typeof MoreSettingsRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/salat-nabi': {
      id: '/more/salat-nabi'
      path: '/salat-nabi'
      fullPath: '/more/salat-nabi'
      preLoaderRoute: typeof MoreSalatNabiRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/ruqyah': {
      id: '/more/ruqyah'
      path: '/ruqyah'
      fullPath: '/more/ruqyah'
      preLoaderRoute: typeof MoreRuqyahRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/quran-learning': {
      id: '/more/quran-learning'
      path: '/quran-learning'
      fullPath: '/more/quran-learning'
      preLoaderRoute: typeof MoreQuranLearningRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/qibla': {
      id: '/more/qibla'
      path: '/qibla'
      fullPath: '/more/qibla'
      preLoaderRoute: typeof MoreQiblaRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/prophets-stories': {
      id: '/more/prophets-stories'
      path: '/prophets-stories'
      fullPath: '/more/prophets-stories'
      preLoaderRoute: typeof MoreProphetsStoriesRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/prayer-times': {
      id: '/more/prayer-times'
      path: '/prayer-times'
      fullPath: '/more/prayer-times'
      preLoaderRoute: typeof MorePrayerTimesRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/names': {
      id: '/more/names'
      path: '/names'
      fullPath: '/more/names'
      preLoaderRoute: typeof MoreNamesRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/islamic-education': {
      id: '/more/islamic-education'
      path: '/islamic-education'
      fullPath: '/more/islamic-education'
      preLoaderRoute: typeof MoreIslamicEducationRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/hijri-calendar': {
      id: '/more/hijri-calendar'
      path: '/hijri-calendar'
      fullPath: '/more/hijri-calendar'
      preLoaderRoute: typeof MoreHijriCalendarRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/downloads': {
      id: '/more/downloads'
      path: '/downloads'
      fullPath: '/more/downloads'
      preLoaderRoute: typeof MoreDownloadsRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/athkar': {
      id: '/more/athkar'
      path: '/athkar'
      fullPath: '/more/athkar'
      preLoaderRoute: typeof MoreAthkarRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/hadith/': {
      id: '/more/hadith/'
      path: '/hadith'
      fullPath: '/more/hadith/'
      preLoaderRoute: typeof MoreHadithIndexRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/hadith/$book': {
      id: '/more/hadith/$book'
      path: '/hadith/$book'
      fullPath: '/more/hadith/$book'
      preLoaderRoute: typeof MoreHadithBookRouteImport
      parentRoute: typeof MoreRoute
    }
    '/api/public/version': {
      id: '/api/public/version'
      path: '/api/public/version'
      fullPath: '/api/public/version'
      preLoaderRoute: typeof ApiPublicVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tts/salat-nabi.mp3': {
      id: '/api/public/tts/salat-nabi.mp3'
      path: '/api/public/tts/salat-nabi.mp3'
      fullPath: '/api/public/tts/salat-nabi.mp3'
      preLoaderRoute: typeof ApiPublicTtsSalatNabiDotmp3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tts/ruqyah': {
      id: '/api/public/tts/ruqyah'
      path: '/api/public/tts/ruqyah'
      fullPath: '/api/public/tts/ruqyah'
      preLoaderRoute: typeof ApiPublicTtsRuqyahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tts/prophet-story': {
      id: '/api/public/tts/prophet-story'
      path: '/api/public/tts/prophet-story'
      fullPath: '/api/public/tts/prophet-story'
      preLoaderRoute: typeof ApiPublicTtsProphetStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/unsubscribe': {
      id: '/api/public/push/unsubscribe'
      path: '/api/public/push/unsubscribe'
      fullPath: '/api/public/push/unsubscribe'
      preLoaderRoute: typeof ApiPublicPushUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/subscribe': {
      id: '/api/public/push/subscribe'
      path: '/api/public/push/subscribe'
      fullPath: '/api/public/push/subscribe'
      preLoaderRoute: typeof ApiPublicPushSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/cron': {
      id: '/api/public/push/cron'
      path: '/api/public/push/cron'
      fullPath: '/api/public/push/cron'
      preLoaderRoute: typeof ApiPublicPushCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/announce-update': {
      id: '/api/public/push/announce-update'
      path: '/api/public/push/announce-update'
      fullPath: '/api/public/push/announce-update'
      preLoaderRoute: typeof ApiPublicPushAnnounceUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MoreRouteChildren {
  MoreAthkarRoute: typeof MoreAthkarRoute
  MoreDownloadsRoute: typeof MoreDownloadsRoute
  MoreHijriCalendarRoute: typeof MoreHijriCalendarRoute
  MoreIslamicEducationRoute: typeof MoreIslamicEducationRoute
  MoreNamesRoute: typeof MoreNamesRoute
  MorePrayerTimesRoute: typeof MorePrayerTimesRoute
  MoreProphetsStoriesRoute: typeof MoreProphetsStoriesRoute
  MoreQiblaRoute: typeof MoreQiblaRoute
  MoreQuranLearningRoute: typeof MoreQuranLearningRoute
  MoreRuqyahRoute: typeof MoreRuqyahRoute
  MoreSalatNabiRoute: typeof MoreSalatNabiRoute
  MoreSettingsRoute: typeof MoreSettingsRoute
  MoreTasbeehRoute: typeof MoreTasbeehRoute
  MoreThemesRoute: typeof MoreThemesRoute
  MoreZakatCalculatorRoute: typeof MoreZakatCalculatorRoute
  MoreIndexRoute: typeof MoreIndexRoute
  MoreHadithBookRoute: typeof MoreHadithBookRoute
  MoreHadithIndexRoute: typeof MoreHadithIndexRoute
}

const MoreRouteChildren: MoreRouteChildren = {
  MoreAthkarRoute: MoreAthkarRoute,
  MoreDownloadsRoute: MoreDownloadsRoute,
  MoreHijriCalendarRoute: MoreHijriCalendarRoute,
  MoreIslamicEducationRoute: MoreIslamicEducationRoute,
  MoreNamesRoute: MoreNamesRoute,
  MorePrayerTimesRoute: MorePrayerTimesRoute,
  MoreProphetsStoriesRoute: MoreProphetsStoriesRoute,
  MoreQiblaRoute: MoreQiblaRoute,
  MoreQuranLearningRoute: MoreQuranLearningRoute,
  MoreRuqyahRoute: MoreRuqyahRoute,
  MoreSalatNabiRoute: MoreSalatNabiRoute,
  MoreSettingsRoute: MoreSettingsRoute,
  MoreTasbeehRoute: MoreTasbeehRoute,
  MoreThemesRoute: MoreThemesRoute,
  MoreZakatCalculatorRoute: MoreZakatCalculatorRoute,
  MoreIndexRoute: MoreIndexRoute,
  MoreHadithBookRoute: MoreHadithBookRoute,
  MoreHadithIndexRoute: MoreHadithIndexRoute,
}

const MoreRouteWithChildren = MoreRoute._addFileChildren(MoreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DataPolicyRoute: DataPolicyRoute,
  FavoritesRoute: FavoritesRoute,
  ListenRoute: ListenRoute,
  MoreRoute: MoreRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProgressRoute: ProgressRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  ReadSurahNumberRoute: ReadSurahNumberRoute,
  ReadIndexRoute: ReadIndexRoute,
  ApiPublicVersionRoute: ApiPublicVersionRoute,
  ApiPublicPushAnnounceUpdateRoute: ApiPublicPushAnnounceUpdateRoute,
  ApiPublicPushCronRoute: ApiPublicPushCronRoute,
  ApiPublicPushSubscribeRoute: ApiPublicPushSubscribeRoute,
  ApiPublicPushUnsubscribeRoute: ApiPublicPushUnsubscribeRoute,
  ApiPublicTtsProphetStoryRoute: ApiPublicTtsProphetStoryRoute,
  ApiPublicTtsRuqyahRoute: ApiPublicTtsRuqyahRoute,
  ApiPublicTtsSalatNabiDotmp3Route: ApiPublicTtsSalatNabiDotmp3Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
